/* Generated by wayland-scanner 1.21.0 */

#ifndef KIOSK_SHELL_DPMS_MANAGEMENT_SERVER_PROTOCOL_H
#define KIOSK_SHELL_DPMS_MANAGEMENT_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_kiosk_shell_dpms_management The kiosk_shell_dpms_management protocol
 * @section page_ifaces_kiosk_shell_dpms_management Interfaces
 * - @subpage page_iface_kiosk_shell_dpms_manager - turn display on and off
 */
struct kiosk_shell_dpms_manager;

#ifndef KIOSK_SHELL_DPMS_MANAGER_INTERFACE
#define KIOSK_SHELL_DPMS_MANAGER_INTERFACE
/**
 * @page page_iface_kiosk_shell_dpms_manager kiosk_shell_dpms_manager
 * @section page_iface_kiosk_shell_dpms_manager_desc Description
 * @section page_iface_kiosk_shell_dpms_manager_api API
 * See @ref iface_kiosk_shell_dpms_manager.
 */
/**
 * @defgroup iface_kiosk_shell_dpms_manager The kiosk_shell_dpms_manager interface
 */
extern const struct wl_interface kiosk_shell_dpms_manager_interface;
#endif

/**
 * @ingroup iface_kiosk_shell_dpms_manager
 * @struct kiosk_shell_dpms_manager_interface
 */
struct kiosk_shell_dpms_manager_interface {
	/**
	 */
	void (*set_mode)(struct wl_client *client,
			 struct wl_resource *resource,
			 uint32_t mode);
};


/**
 * @ingroup iface_kiosk_shell_dpms_manager
 */
#define KIOSK_SHELL_DPMS_MANAGER_SET_MODE_SINCE_VERSION 1

#ifdef  __cplusplus
}
#endif

#endif
